In [72]:
import numpy as np
import pandas as pd

In [73]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [74]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [75]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [76]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [77]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [78]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],train_size=0.2)

In [79]:
X_train

    age  gender  fever   cough       city
49   44    Male  104.0    Mild     Mumbai
45   72    Male   99.0    Mild  Bangalore
42   27    Male  100.0    Mild      Delhi
30   15    Male  101.0    Mild      Delhi
22   71  Female   98.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
90   59  Female   99.0  Strong      Delhi
69   73  Female  103.0    Mild      Delhi
74   34  Female  104.0  Strong      Delhi
72   83  Female  101.0    Mild    Kolkata
16   69  Female  103.0    Mild    Kolkata
18   64  Female   98.0    Mild  Bangalore
76   80    Male  100.0    Mild  Bangalore
66   51    Male  104.0    Mild    Kolkata
79   48  Female  103.0    Mild    Kolkata
82   24    Male   98.0    Mild    Kolkata
81   65    Male   99.0    Mild      Delhi
75    5    Male  102.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai

### when i don't know how to use Column Transformation

In [80]:
# adding simple imputer to fever column
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data 
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[104.],
       [ 99.],
       [100.],
       [101.],
       [ 98.],
       [100.],
       [104.],
       [ 99.],
       [103.],
       [104.],
       [101.],
       [103.],
       [ 98.],
       [100.],
       [104.],
       [103.],
       [ 98.],
       [ 99.],
       [102.],
       [ 99.]])

In [81]:
X_train_fever.shape

(20, 1)

In [82]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(20, 1)

In [83]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first')
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(20, 4)

In [84]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(20, 1)

### If you know column Transformer

In [91]:
from sklearn.compose import ColumnTransformer

In [93]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [94]:
transformer.fit_transform(X_train)

array([[104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  71.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.]])

In [95]:
transformer.transform(X_test)

array([[ 98.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  73.  ],
       [ 99.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  49.  ],
       [102.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,  74.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  19.  ],
       [103.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  16.  ],
       [ 98.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  31.  ],
       [100.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   5.  ],
       [102.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  64.  ],
       [101.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  42.  ],
       [104.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   6.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  13.  ],
       [101.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  19.  ],
       [100.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  27.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  16.  ],
       [100.95,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  84.  ],
       [102.  ,   1.  ,   1.  ,   1.  ,   0.  ,   0.  ,  20.  ],
       [102.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  82.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  81.  ],
       [101.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  51.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,  42.  ],
       [ 98.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  80.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  51.  ],
       [100.95,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,  23.  ],
       [103.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  83.  ],
       [ 99.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  25.  ],
       [100.95,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  34.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  65.  ],
       [101.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  34.  ],
       [100.95,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  42.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  20.  ],
       [100.95,   1.  ,   1.  ,   0.  ,   1.  ,   0.  ,  79.  ],
       [ 98.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  40.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  10.  ],
       [ 99.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  65.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  38.  ],
       [ 98.  ,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  83.  ],
       [100.95,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  20.  ],
       [103.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  50.  ],
       [100.95,   0.  ,   1.  ,   1.  ,   0.  ,   0.  ,  38.  ],
       [101.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  47.  ],
       [100.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  10.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  69.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  19.  ],
       [102.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  82.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  47.  ],
       [ 98.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  65.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  81.  ],
       [ 98.  ,   1.  ,   1.  ,   0.  ,   1.  ,   0.  ,  34.  ],
       [102.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  69.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   8.  ],
       [101.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  14.  ],
       [ 99.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  66.  ],
       [103.  ,   1.  ,   1.  ,   0.  ,   1.  ,   0.  ,  70.  ],
       [104.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  18.  ],
       [102.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  24.  ],
       [ 99.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  14.  ],
       [102.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  49.  ],
       [104.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  54.  ],
       [103.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  46.  ],
       [103.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  60.  ],
       [ 98.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  12.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  11.  ],
       [104.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  12.  ],
       [100.95,   1.  ,   1.  ,   0.  ,   1.  ,   0.  ,  71.  ],
       [ 98.  ,   1.  ,   1.  ,   0.  ,   0.  ,   1.  ,  23.  ],
       [100.95,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  75.  ],
       [100.95,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  82.  ],
       [102.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  33.  ],
       [100.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  19.  ],
       [100.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  27.  ],
       [100.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  11.  ],
       [101.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  64.  ],
       [101.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  49.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,   5.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  25.  ],
       [104.  ,   1.  ,   0.  ,   0.  ,   0.  ,   0.  ,  56.  ],
       [ 98.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  26.  ],
       [104.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  17.  ],
       [101.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  68.  ],
       [ 99.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  22.  ]])