#### What is an Imbalanced Dataset?
- Consider a classification problem where the output is categorical. For example, in a binary classification problem, the output can be one of two categories.

- Suppose we have 1000 data points, with the output being either "yes" or "no". If 900 data points are "yes" and 100 are "no", this represents a 9:1 ratio. This situation is called an imbalanced dataset because one class significantly outnumbers the other.

#### Problems Caused by Imbalanced Datasets
When training a machine learning model on an imbalanced dataset, the model tends to be biased towards the majority class. This bias can reduce the model's ability to correctly predict the minority class, which is often the class of interest. Therefore, it is necessary to address the imbalance to improve model performance.

#### Techniques to Handle Imbalanced Datasets
Two common techniques to handle imbalanced datasets are:
- Upsampling: Increasing the number of data points in the minority class.
- Downsampling: Reducing the number of data points in the majority class.

We will first perform upsampling and then downsampling to understand both approaches.

In [1]:
""" Creating an Imbalanced Dataset
We start by creating a dataset with 1000 data points, where 90% belong to class zero and 10% belong to class one. This means 900 data points are class zero and 100 are class one.
We use numpy and pandas libraries, and set a random seed for reproducibility. The dataset includes two features generated from normal distributions and a target variable indicating the class.
"""

import numpy as np
import pandas as pd

#set the random send for reproducibility
np.random.seed(123)

#create a dataframe with two classes
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [3]:
# Create my dataframe with imbalanced dataset 
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0,scale=1,size=n_class_0),
    'feature_2': np.random.normal(loc = 0,scale=1,size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0,scale=1,size=n_class_1),
    'feature_2': np.random.normal(loc = 0,scale=1,size=n_class_1),
    'target': [1] * n_class_1 
})

In [4]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [5]:
df.head()
df.tail()

     feature_1  feature_2  target
995  -0.623629   0.845701       1
996   0.239810  -1.119923       1
997  -0.868240  -0.359297       1
998   0.902006  -1.609695       1
999   0.697490   0.013570       1

In [6]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Upsampling

In [7]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [8]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority,replace=True,
         n_samples=len(df_majority),
         random_state=42)

In [9]:
df_minority_upsampled.shape
df_minority_upsampled.head()

     feature_1  feature_2  target
951  -0.874146  -0.156083       1
992   0.196570  -0.602575       1
914  -0.067830   0.998053       1
971   0.272825   1.034197       1
960   0.870056  -0.449515       1

In [10]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])

In [11]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

###  Down Sampling

In [12]:
import numpy as np
import pandas as pd

#set the random send for reproducibility
np.random.seed(123)

#create a dataframe with two classes
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0,scale=1,size=n_class_0),
    'feature_2': np.random.normal(loc = 0,scale=1,size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc = 0,scale=1,size=n_class_1),
    'feature_2': np.random.normal(loc = 0,scale=1,size=n_class_1),
    'target': [1] * n_class_1 
})

In [13]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [14]:
from sklearn.utils import resample
df_manjority_downsampled = resample(df_majority,replace=False,
         n_samples=len(df_minority),
         random_state=42)

In [15]:
df_manjority_downsampled.shape
df_manjority_downsampled.head()

     feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0

In [16]:
df_downsampled = pd.concat([df_minority,df_manjority_downsampled])

In [17]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64

### Handling Imbalance Dataset Using SMOTE

### SMOTE(Synthetic Minority OverSampling Technique)
- SMOTE(Synthetic Minority OverSampling Technique) is a Technique used in machine learning ti address imbalanced datasets where the minority class has significantly fewer instances than the majority class. SMPTE involves generating Synthetic instances of the minority class by interpolating b/w Existing instances.

In [18]:
from sklearn.datasets import make_classification

In [19]:
X,y = make_classification(n_samples=1000,n_redundant=0,n_features=2,n_clusters_per_class=1,
                    weights=[0.90],random_state=12)
X #independent feature 
y # dependent feature

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
import pandas as pd
import numpy as np

In [21]:
df1 = pd.DataFrame(X,columns=['f1','f2'])
df2 = pd.DataFrame(y,columns=['target'])
final_df = pd.concat([df1,df2],axis=1)